server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=devatevent
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 12345678
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
    #hibernate:
      #ddl-auto: update
management:
  endpoint:
    health:
      show-details: always